const path = require('path')
const context = require('../helpers/context')
const Base = require('../../src/base/base')
const Container = require('../../src/container')
const Application = require('../../src/foundation/application')
const Config = require('../../src/config')
const Messenger = require('../../src/cluster/messenger')
const Request = require('../../src/request')
const Response = require('../../src/response')
const Redirect = require('../../src/response/redirect')

const _app = new Application(path.resolve(__dirname, '../'))
_app.initialize()

describe('base/base', () => {
  Container.get('config', [])
  const ctx = context({ url: '/store/shoes?page=2&color=blue' })
  const obj = new Base()
  obj.setCtx(ctx)
  it('base instance properties', () => {
    expect(obj.app).toBeInstanceOf(Application)
    expect(obj.config).toBeInstanceOf(Config)
    expect(obj.messenger).toBeInstanceOf(Messenger)
    expect(obj.request).toBeInstanceOf(Request)
    expect(obj.ctx).toBe(ctx)
    expect(obj.response).toBeInstanceOf(Response)
    expect(obj.redirect).toBeInstanceOf(Redirect)
  })
})
